import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { prepareCalculationData } from './calculateBackupDocument';

export const generateCalculationsPDF = (data) => {
  const calcData = prepareCalculationData(data);
  const doc = new jsPDF();

  // Header
  doc.setFillColor(4, 120, 87); // Emerald 700
  doc.rect(0, 0, 210, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("Engineering Design Calculations", 14, 13);
  
  // Project Info
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(12);
  doc.text(`Project: ${calcData.projectName}`, 14, 30);
  doc.setFontSize(10);
  doc.text(`Date: ${calcData.date}`, 14, 36);
  doc.text(`Generated by: EDI Enviro & Engineering`, 14, 42);

  let yPos = 50;

  calcData.sections.forEach((section) => {
    // Section Title
    doc.setFontSize(12);
    doc.setTextColor(4, 120, 87);
    doc.setFont(undefined, 'bold');
    doc.text(section.title, 14, yPos);
    
    // Table
    doc.autoTable({
      startY: yPos + 2,
      head: [section.rows[0]],
      body: section.rows.slice(1),
      theme: 'grid',
      headStyles: { fillColor: [4, 120, 87], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 14, right: 14 }
    });

    yPos = doc.lastAutoTable.finalY + 15;
    
    // Page break check simple logic
    if (yPos > 250) {
        doc.addPage();
        yPos = 20;
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Confidential - EDI Enviro Internal Use Only', 14, 285);
      doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
  }

  doc.save(`Calculations_${calcData.projectName.replace(/\s+/g, '_')}.pdf`);
};